name : first
on : push
jobs:
   job1:
       name : first job
       runs-on: windows-latest
       steps:
           uses : actions/checkout@latest
           run : "Get-ChildItem Env: | Sort-Object Name"
   job2:
       name : second job
       runs-on : ubuntu-latest
       steps:
           uses : actions/checkout@latest
           run : env | sort
           
           
       
 
